language: java

jdk:
  - oraclejdk8

before_install:
  - gradleVersion=3.2
  - wget http://downloads.gradle.org/distributions/gradle-$gradleVersion-bin.zip
  - unzip -qq gradle-$gradleVersion-bin.zip
  - $PWD/gradle-$gradleVersion/bin/gradle wrapper

install: ./gradlew check
